# Generated by Django 5.1.1 on 2024-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_worktimetable_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="action_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
