# Generated by Django 5.1.1 on 2025-02-16 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_worktimetable_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hopital_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hopital',
                'verbose_name_plural': 'hopitals',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialite',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('ANE', 'Anesthésiologie'), ('CAR', 'Cardiologie'), ('DERM', 'Dermatologie'), ('ENDO', 'Endocrinologie'), ('GA_EN', 'Gastro-entérologie'), ('GE_ME', 'Génétique médicale'), ('GER', 'Gériatrie'), ('HE', 'Hématologie'), ('IMM', 'Immunologie'), ('NEP', 'Néphrologie'), ('NEU', 'Neurologie'), ('ONC', 'Oncologie'), ('PE', 'Pédiatrie'), ('PHY', 'Physiatrie'), ('PNEU', 'Pneumologie'), ('PSY', 'psychiatrie'), ('RHU', 'Rhumatologie')], max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.hopital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialite',
            field=models.ManyToManyField(related_name='doctors', to='appointment.specialty'),
        ),
    ]
