# Generated by Django 5.1.1 on 2025-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_doctor_rating_alter_hopital_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
