# Generated by Django 5.1.6 on 2025-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
