# Generated by Django 5.1.6 on 2025-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profil_user_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
