# Generated by Django 5.2 on 2025-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('bif', 'Bif'), ('usd', 'Usd'), ('eur', 'Eur')], default='bif', max_length=250),
        ),
    ]
