# Generated by Django 5.2 on 2025-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctor_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('suspended', 'Suspended'), ('refused', 'Refused')], default='pending'),
        ),
    ]
