# Generated by Django 5.2 on 2025-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitie',
            name='name',
            field=models.CharField(choices=[('ANE', 'Anesthésiologie'), ('CAR', 'Cardiologie'), ('DERM', 'Dermatologie'), ('ENDO', 'Endocrinologie'), ('GA_EN', 'Gastro-entérologie'), ('GE_ME', 'Génétique médicale'), ('GER', 'Gériatrie'), ('HE', 'Hématologie'), ('IMM', 'Immunologie'), ('NEP', 'Néphrologie'), ('NEU', 'Neurologie'), ('ONC', 'Oncologie'), ('PE', 'Pédiatrie'), ('PHY', 'Physiatrie'), ('PNEU', 'Pneumologie'), ('PSY', 'psychiatrie'), ('RHU', 'Rhumatologie')], max_length=250),
        ),
    ]
