# Generated by Django 5.2 on 2025-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_specialitie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitie',
            name='name',
            field=models.CharField(choices=[('anesthésiologie', 'Anesthésiologie'), ('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('endocrinologie', 'Endocrinologie'), ('gastro-entérologie', 'Gastro-entérologie'), ('génétique médicale', 'Génétique médicale'), ('gériatrie', 'Gériatrie'), ('hématologie', 'Hématologie'), ('immunologie', 'Immunologie'), ('néphrologie', 'Néphrologie'), ('neurologie', 'Neurologie'), ('oncologie', 'Oncologie'), ('pédiatrie', 'Pédiatrie'), ('physiatrie', 'Physiatrie'), ('pneumologie', 'Pneumologie'), ('psychiatrie', 'Psychiatrie'), ('rhumatologie', 'Rhumatologie')], max_length=250),
        ),
    ]
